version: "3.8"

services:
    app:
        image: laravel
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            target: backend
        volumes:
            - .:/var/www/html
        ports:
            - 80:80
        depends_on:
            - db
    db:
        image: mysql:8.0
        ports:
            - 63306:3306
        environment:
            - TZ=Asia/Tokyo
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=docker
            - MYSQL_PASSWORD=docker
        volumes:
            - mysql:/var/lib/mysql
volumes:
    mysql: